"""ilk_kurulum

Revision ID: 0642822d5658
Revises: 
Create Date: 2026-08-17 14:33:26.030589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0642822d5658'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('password_policy_note', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_users_email'), 'platform_users', ['email'], unique=True)
    op.create_table('assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['platform_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sap_systems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('sid', sa.String(length=3), nullable=True),
    sa.Column('environment', sa.String(length=10), nullable=True),
    sa.Column('system_type', sa.String(length=50), nullable=True),
    sa.Column('app_server', sa.String(length=255), nullable=True),
    sa.Column('instance_number', sa.String(length=2), nullable=True),
    sa.Column('sap_router', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vpn_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('vpn_type', sa.String(length=100), nullable=True),
    sa.Column('gateway_address', sa.String(length=255), nullable=True),
    sa.Column('vault_secret_path', sa.String(length=255), nullable=True),
    sa.Column('config_file_url', sa.String(length=255), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sap_clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('system_id', sa.UUID(), nullable=True),
    sa.Column('client_number', sa.String(length=3), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['sap_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sap_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('user_type', sa.String(length=50), nullable=True),
    sa.Column('vault_secret_path', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['sap_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sap_users')
    op.drop_table('sap_clients')
    op.drop_table('vpn_profiles')
    op.drop_table('sap_systems')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_platform_users_email'), table_name='platform_users')
    op.drop_table('platform_users')
    op.drop_table('customers')
    # ### end Alembic commands ###
