"""Tum tablolara comment ve description alanlari eklendi

Revision ID: 1f172d19e2fb
Revises: 41e2f35f73cb
Create Date: 2026-08-19 12:18:51.271326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f172d19e2fb'
down_revision: Union[str, None] = '41e2f35f73cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('sap_clients', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('sap_systems', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('sap_users', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('vpn_profiles', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vpn_profiles', 'comment')
    op.drop_column('sap_users', 'comment')
    op.drop_column('sap_systems', 'comment')
    op.drop_column('sap_clients', 'comment')
    op.drop_column('customers', 'comment')
    # ### end Alembic commands ###
