"""assigned_customer_ids eklendi

Revision ID: 41e2f35f73cb
Revises: 0642822d5658
Create Date: 2026-08-18 16:30:59.651814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41e2f35f73cb'
down_revision: Union[str, None] = '0642822d5658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_users', sa.Column('assigned_customer_ids', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_users', 'assigned_customer_ids')
    # ### end Alembic commands ###
